#%RAML 1.0 Trait
usage: Apply this trait to get Anypoint Credentials from the user.
description: This trait will enforce Anypoint Credential capture from the customer. The API will use the details to connect to the Anypoint platform and gather details. The provided credentail must have adequate read access for almost everything of the platform.
headers:
  X-AUTH-STRATEGY:
    description: The authentication strategy
    enum: ["connectedApp", "userPassword", "refreshToken", "accessToken"]
    example: connectedApp
    required: true
  X-CONNECTED-APP-CLIENT_ID:
    description: The client_id of the connected App. It is mandatory for the connectedApp and refreshToken authentication strategy
    type: string
    example: a934bnj3n45ou5i7nln443b54b
    required: false
  X-CONNECTED-APP-CLIENT_SECRET:
    description: The client_secret of the connected App. It is mandatory for the connectedApp and refreshToken authentication strategy
    type: string
    example: kjihi56b1212vghc35b34kb45k
    required: false
  X-CONNECTED-APP-REFRESH-TOKEN:
    description: The refresh token of the connected App. It is mandatory for the refreshToken authentication strategy
    type: string
    example: kjihi56b1212vghc35b34kb45k
    required: false
  X-USER-NAME:
    description: Username of the platform. It is mandatory for the userPassword authentication strategy
    type: string
    example: username
    required: false
  X-PASSWORD:
    description: Password of the platform. It is mandatory for the userPassword authentication strategy
    type: string
    example: username
    required: false
  X-ACCESS-TOKEN:
    description: Access Token received from the Anypoint platform. It is mandatory for the accessToken authentication strategy. You can find the full documentation on how to get an access_token here - https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/minor/1.0/pages/Authentication/
    type: string
    example: 217347923974828304230423042300423hwhbdswsdhk
    required: false